<a href="https://colab.research.google.com/github/kunjkinger/machine-learning-projects/blob/nlp/latent_dirichlet_allocation_nlp.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('npr.csv')

In [3]:
df.head()

Article
0  In the Washington of 2016, even when the polic...
1    Donald Trump has used Twitter  —   his prefe...
2    Donald Trump is unabashedly praising Russian...
3  Updated at 2:50 p. m. ET, Russian President Vl...
4  From photography, illustration and video, to d...

In [4]:
df['Article'][0]

'In the Washington of 2016, even when the policy can be bipartisan, the politics cannot. And in that sense, this year shows little sign of ending on Dec. 31. When President Obama moved to sanction Russia over its alleged interference in the U. S. election just concluded, some Republicans who had long called for similar or more severe measures could scarcely bring themselves to approve. House Speaker Paul Ryan called the Obama measures ”appropriate” but also ”overdue” and ”a prime example of this administration’s ineffective foreign policy that has left America weaker in the eyes of the world.” Other GOP leaders sounded much the same theme. ”[We have] been urging President Obama for years to take strong action to deter Russia’s worldwide aggression, including its   operations,” wrote Rep. Devin Nunes,  . chairman of the House Intelligence Committee. ”Now with just a few weeks left in office, the president has suddenly decided that some stronger measures are indeed warranted.” Appearing 

In [5]:
from sklearn.feature_extraction.text import CountVectorizer

In [6]:
cv = CountVectorizer(max_df=0.9,min_df=2,stop_words='english')

In [7]:
dtm = cv.fit_transform(df['Article'])

In [8]:
dtm

<11992x54777 sparse matrix of type '<class 'numpy.int64'>'
	with 3033388 stored elements in Compressed Sparse Row format>

In [9]:
from sklearn.decomposition import LatentDirichletAllocation

In [10]:
lda = LatentDirichletAllocation(n_components=7,random_state=42)

In [11]:
lda.fit(dtm)

LatentDirichletAllocation(batch_size=128, doc_topic_prior=None,
                          evaluate_every=-1, learning_decay=0.7,
                          learning_method='batch', learning_offset=10.0,
                          max_doc_update_iter=100, max_iter=10,
                          mean_change_tol=0.001, n_components=7, n_jobs=None,
                          perp_tol=0.1, random_state=42, topic_word_prior=None,
                          total_samples=1000000.0, verbose=0)

In [13]:
#grab the vocab of words
len(cv.get_feature_names())

54777

In [15]:
type(cv.get_feature_names())

list

In [16]:
cv.get_feature_names()[5000]

'bask'

In [18]:
import random

random_word_id = random.randint(0,54777)
cv.get_feature_names()[random_word_id]

'crowded'

In [19]:
#grab the topics
len(lda.components_)

7

In [20]:
type(lda.components_)

numpy.ndarray

In [22]:
lda.components_.shape # this means 7 topics by 54777 words

(7, 54777)

In [38]:
#grab the topic
single_topic = lda.components_[0]

In [24]:
single_topic.argsort()

array([ 2475, 18302, 35285, ..., 22673, 42561, 42993])

In [25]:
#example of argsort
import numpy as np


In [26]:
arr = np.array([10,200,1])

In [28]:
arr.argsort() # this means sorting with the indexing location in ascending order

array([2, 0, 1])

In [29]:
#first argsort does sorting with the indexing location in ascending order
#top 10 values ( 10 greatest values)
#last 10 values of argsort  
single_topic.argsort()[-10:] # grab the last 10 values of  .argsort()

array([33390, 36310, 21228, 10425, 31464,  8149, 36283, 22673, 42561,
       42993])

In [34]:
top_twenty_words = single_topic.argsort()[-20:]

In [35]:
for index in top_twenty_words:
  print(cv.get_feature_names()[index])

president
state
tax
insurance
trump
companies
money
year
federal
000
new
percent
government
company
million
care
people
health
said
says


In [36]:
#grab the words with the highest prob per topic


In [37]:
for index, topic in enumerate(lda.components_):
  print(f"THE TOP 15 WORDS DOR TOPIC #  {index}")
  print([cv.get_feature_names()[index] for index in topic.argsort()[-15:]])
  print('\n')
  print('\n')

THE TOP 15 WORDS DOR TOPIC #  0
['companies', 'money', 'year', 'federal', '000', 'new', 'percent', 'government', 'company', 'million', 'care', 'people', 'health', 'said', 'says']




THE TOP 15 WORDS DOR TOPIC #  1
['military', 'house', 'security', 'russia', 'government', 'npr', 'reports', 'says', 'news', 'people', 'told', 'police', 'president', 'trump', 'said']




THE TOP 15 WORDS DOR TOPIC #  2
['way', 'world', 'family', 'home', 'day', 'time', 'water', 'city', 'new', 'years', 'food', 'just', 'people', 'like', 'says']




THE TOP 15 WORDS DOR TOPIC #  3
['time', 'new', 'don', 'years', 'medical', 'disease', 'patients', 'just', 'children', 'study', 'like', 'women', 'health', 'people', 'says']




THE TOP 15 WORDS DOR TOPIC #  4
['voters', 'vote', 'election', 'party', 'new', 'obama', 'court', 'republican', 'campaign', 'people', 'state', 'president', 'clinton', 'said', 'trump']




THE TOP 15 WORDS DOR TOPIC #  5
['years', 'going', 've', 'life', 'don', 'new', 'way', 'music', 'really', 't

In [41]:
topic_results = lda.transform(dtm)

In [42]:
topic_results.shape

(11992, 7)

In [44]:
  topic_results[0].round(2) # highest prob showing

array([0.02, 0.68, 0.  , 0.  , 0.3 , 0.  , 0.  ])

In [45]:
topic_results[0].argmax()

1

In [46]:
df['topic'] = topic_results.argmax(axis=1)

In [47]:
df

Article  topic
0      In the Washington of 2016, even when the polic...      1
1        Donald Trump has used Twitter  —   his prefe...      1
2        Donald Trump is unabashedly praising Russian...      1
3      Updated at 2:50 p. m. ET, Russian President Vl...      1
4      From photography, illustration and video, to d...      2
...                                                  ...    ...
11987  The number of law enforcement officers shot an...      1
11988    Trump is busy these days with victory tours,...      4
11989  It’s always interesting for the Goats and Soda...      3
11990  The election of Donald Trump was a surprise to...      4
11991  Voters in the English city of Sunderland did s...      0

[11992 rows x 2 columns]